/*
 * Copyright (c) 2015, Haiyang Li.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.landawn.abacus.query;

import java.util.List;
import java.util.Map;
import java.util.Set;

import com.landawn.abacus.query.SqlDialect.SqlPolicy;
import com.landawn.abacus.query.condition.SubQuery;
import com.landawn.abacus.util.ImmutableList;
import com.landawn.abacus.util.N;

/**
 * Internal snapshot of a complete, read-only SELECT produced by a consumed {@link SqlBuilder}.
 * Besides the rendered SQL and parameter values, it retains the source builder's SQL policy and
 * generated-placeholder metadata so a parent builder can preserve binding order and rewrite named
 * parameters when collisions occur.
 *
 * <p>The parameter list originates from the defensively copied {@link AbstractQueryBuilder.SP}
 * returned by the source builder. The placeholder maps and set are retained by reference rather
 * than copied or wrapped: ownership transfers from the consumed builder to this snapshot, and
 * package code must treat those collections as read-only after construction. Parent composition
 * creates working copies for metadata that may require collision rewriting, allowing the same
 * snapshot to be composed more than once without altering it.</p>
 *
 * <p>This package-private type is an implementation detail; public callers receive it as a
 * {@link SubQuery}.</p>
 */
final class SubQuerySnapshot extends SubQuery {

    /** Stable parameter values copied by {@link AbstractQueryBuilder.SP} before this snapshot is created. */
    final ImmutableList<Object> parameters;

    /** SQL policy used to render the stored query and any generated placeholders. */
    final SqlPolicy sqlPolicy;

    /** Whether the stored SQL contains a placeholder generated by the source builder. */
    final boolean hasGeneratedParameterPlaceholder;

    /** Owned occurrence counts for generated named parameters; treated as read-only after construction. */
    final Map<String, Integer> namedParameterNameOccurrences;

    /** Owned generated parameter names; treated as read-only after construction. */
    final Set<String> generatedNamedParameterNames;

    /** Owned rendered tokens for generated named parameters; treated as read-only after construction. */
    final Map<String, String> renderedNamedParameterTokens;

    /**
     * Creates a builder-backed snapshot. The supplied placeholder metadata collections become owned
     * by this instance and must not be mutated afterward; they are intentionally not defensively copied.
     *
     * @param sql the complete, read-only SELECT text
     * @param parameters the stable parameter values captured by the source builder
     * @param sqlPolicy the policy used to render {@code sql}
     * @param hasGeneratedParameterPlaceholder whether {@code sql} contains a generated placeholder
     * @param namedParameterNameOccurrences occurrence counts for generated named parameters
     * @param generatedNamedParameterNames names generated by the source builder
     * @param renderedNamedParameterTokens rendered placeholder tokens keyed by generated name
     */
    SubQuerySnapshot(final String sql, final List<Object> parameters, final SqlPolicy sqlPolicy, final boolean hasGeneratedParameterPlaceholder,
            final Map<String, Integer> namedParameterNameOccurrences, final Set<String> generatedNamedParameterNames,
            final Map<String, String> renderedNamedParameterTokens) {
        super(sql);

        this.parameters = ImmutableList.wrap(parameters);
        this.sqlPolicy = sqlPolicy;
        this.hasGeneratedParameterPlaceholder = hasGeneratedParameterPlaceholder;
        this.namedParameterNameOccurrences = namedParameterNameOccurrences;
        this.generatedNamedParameterNames = generatedNamedParameterNames;
        this.renderedNamedParameterTokens = renderedNamedParameterTokens;
    }

    /** {@inheritDoc} */
    @Override
    public ImmutableList<Object> parameters() {
        return parameters;
    }

    @Override
    public int hashCode() {
        int result = super.hashCode();
        result = 31 * result + parameters.hashCode();
        result = 31 * result + sqlPolicy.hashCode();
        result = 31 * result + Boolean.hashCode(hasGeneratedParameterPlaceholder);
        result = 31 * result + namedParameterNameOccurrences.hashCode();
        result = 31 * result + generatedNamedParameterNames.hashCode();
        result = 31 * result + renderedNamedParameterTokens.hashCode();
        return result;
    }

    @Override
    public boolean equals(final Object obj) {
        if (!super.equals(obj)) {
            return false;
        }

        final SubQuerySnapshot other = (SubQuerySnapshot) obj;
        return hasGeneratedParameterPlaceholder == other.hasGeneratedParameterPlaceholder && sqlPolicy == other.sqlPolicy
                && N.equals(parameters, other.parameters) && N.equals(namedParameterNameOccurrences, other.namedParameterNameOccurrences)
                && N.equals(generatedNamedParameterNames, other.generatedNamedParameterNames)
                && N.equals(renderedNamedParameterTokens, other.renderedNamedParameterTokens);
    }
}
