/*
 * Copyright (c) 2015, Haiyang Li.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.landawn.abacus.query;

import java.util.List;
import java.util.Map;
import java.util.Set;

import com.landawn.abacus.query.SqlDialect.SqlPolicy;
import com.landawn.abacus.query.condition.SubQuery;
import com.landawn.abacus.util.ImmutableList;
import com.landawn.abacus.util.N;

/**
 * Internal snapshot of a complete, syntactically validated SELECT produced by a consumed {@link SqlBuilder}.
 * Besides the rendered SQL and parameter values, it retains the source builder's SQL policy and
 * generated-placeholder metadata so a parent builder can preserve binding order and rewrite named
 * parameters when collisions occur.
 *
 * <p>The parameter list originates from the defensively copied {@link AbstractQueryBuilder.SP}
 * returned by the source builder. The placeholder maps and set are retained by reference rather
 * than copied or wrapped: ownership transfers from the consumed builder to this snapshot, and
 * package code must treat those collections as read-only after construction. Parent composition
 * creates working copies for metadata that may require collision rewriting, allowing the same
 * snapshot to be composed more than once without altering it.</p>
 *
 * <p>This package-private type is an implementation detail; public callers receive it as a
 * {@link SubQuery}.</p>
 */
final class SubQuerySnapshot extends SubQuery {

    /** Stable parameter-list structure copied by {@link AbstractQueryBuilder.SP}; mutable values remain shared. */
    final ImmutableList<Object> parameters;

    /** SQL policy used to render the stored query and any generated placeholders. */
    final SqlPolicy sqlPolicy;

    /** Whether the stored SQL contains a placeholder generated by the source builder. */
    final boolean hasGeneratedParameterPlaceholder;

    /** Whether the source query needs explicit isolation before it can be used as a set-operation operand. */
    final boolean requiresSetOperationIsolation;

    /** Owned occurrence counts for generated named parameters; treated as read-only after construction. */
    final Map<String, Integer> namedParameterNameOccurrences;

    /** Owned generated parameter names; treated as read-only after construction. */
    final Set<String> generatedNamedParameterNames;

    /** Owned rendered tokens for generated named parameters; treated as read-only after construction. */
    final Map<String, String> renderedNamedParameterTokens;

    /**
     * Creates a builder-backed snapshot. The supplied placeholder metadata collections become owned
     * by this instance and must not be mutated afterward; they are intentionally not defensively copied.
     *
     * @param sql the complete, syntactically validated SELECT text
     * @param parameters the stable parameter-list structure captured by the source builder; mutable values remain shared
     * @param sqlPolicy the policy used to render {@code sql}
     * @param hasGeneratedParameterPlaceholder whether {@code sql} contains a generated placeholder
     * @param requiresSetOperationIsolation whether its own compound or terminal clauses require branch isolation
     * @param namedParameterNameOccurrences occurrence counts for generated named parameters
     * @param generatedNamedParameterNames names generated by the source builder
     * @param renderedNamedParameterTokens rendered placeholder tokens keyed by generated name
     * @throws IllegalArgumentException if {@code sql} is {@code null}, empty, or blank
     */
    SubQuerySnapshot(final String sql, final List<Object> parameters, final SqlPolicy sqlPolicy, final boolean hasGeneratedParameterPlaceholder,
            final boolean requiresSetOperationIsolation, final Map<String, Integer> namedParameterNameOccurrences,
            final Set<String> generatedNamedParameterNames, final Map<String, String> renderedNamedParameterTokens) {
        // Builder snapshots already own a validated SQL/parameter pair; bypass only the public raw-SQL
        // constructor's "no unbound placeholders" guard while retaining all builder metadata below.
        super(sql, true);

        this.parameters = ImmutableList.wrap(parameters);
        this.sqlPolicy = sqlPolicy;
        this.hasGeneratedParameterPlaceholder = hasGeneratedParameterPlaceholder;
        this.requiresSetOperationIsolation = requiresSetOperationIsolation;
        this.namedParameterNameOccurrences = namedParameterNameOccurrences;
        this.generatedNamedParameterNames = generatedNamedParameterNames;
        this.renderedNamedParameterTokens = renderedNamedParameterTokens;
    }

    /** {@inheritDoc} */
    @Override
    public ImmutableList<Object> parameters() {
        return parameters;
    }

    /**
     * Returns the hash code of this snapshot, combining the superclass hash code with the
     * parameters, SQL policy, generated-placeholder and branch-isolation flags, and placeholder metadata.
     *
     * @return a hash code consistent with {@link #equals(Object)}
     */
    @Override
    public int hashCode() {
        int result = super.hashCode();
        result = 31 * result + deepParametersHashCode(parameters);
        result = 31 * result + sqlPolicy.hashCode();
        result = 31 * result + Boolean.hashCode(hasGeneratedParameterPlaceholder);
        result = 31 * result + Boolean.hashCode(requiresSetOperationIsolation);
        result = 31 * result + namedParameterNameOccurrences.hashCode();
        result = 31 * result + generatedNamedParameterNames.hashCode();
        result = 31 * result + renderedNamedParameterTokens.hashCode();
        return result;
    }

    /**
     * Compares this snapshot with another object for equality. Two snapshots are equal when the
     * superclass state, parameters, SQL policy, generated-placeholder and branch-isolation flags, and all
     * placeholder metadata collections are equal.
     *
     * @param obj the object to compare with
     * @return {@code true} if {@code obj} is a {@code SubQuerySnapshot} with equal state, {@code false} otherwise
     */
    @Override
    public boolean equals(final Object obj) {
        if (!super.equals(obj)) {
            return false;
        }

        final SubQuerySnapshot other = (SubQuerySnapshot) obj;
        return hasGeneratedParameterPlaceholder == other.hasGeneratedParameterPlaceholder
                && requiresSetOperationIsolation == other.requiresSetOperationIsolation && sqlPolicy == other.sqlPolicy
                && deepParametersEquals(parameters, other.parameters) && N.equals(namedParameterNameOccurrences, other.namedParameterNameOccurrences)
                && N.equals(generatedNamedParameterNames, other.generatedNamedParameterNames)
                && N.equals(renderedNamedParameterTokens, other.renderedNamedParameterTokens);
    }

    /**
     * Element-wise deep hash of the captured parameters, so that array-valued bindings (for example a
     * {@code byte[]}) hash by content, matching {@link #deepParametersEquals(ImmutableList, ImmutableList)}
     * and the raw {@code SubQuery(String, Collection)} path.
     */
    private static int deepParametersHashCode(final ImmutableList<Object> parameters) {
        int h = 1;

        for (final Object parameter : parameters) {
            h = 31 * h + N.deepHashCode(parameter);
        }

        return h;
    }

    /**
     * Element-wise deep equality of the captured parameters (array-valued bindings compare by content).
     */
    private static boolean deepParametersEquals(final ImmutableList<Object> left, final ImmutableList<Object> right) {
        final int size = left.size();

        if (size != right.size()) {
            return false;
        }

        for (int i = 0; i < size; i++) {
            if (!N.deepEquals(left.get(i), right.get(i))) {
                return false;
            }
        }

        return true;
    }
}
